version: "3"
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  server:
    build: ./server
    ports:
      - 8080:8080
  caddy:
    image: caddy:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy:/data
      - .Caddyfile:/etc/caddy/Caddyfile


